- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ playbook_dir }}/../target/*.war"
        dest: "/opt/tomcat/webapps/"

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
